=== dmcmahill/wcalc/sci-wcalc/man.dtd
<!-- $Id: man.dtd,v 1.1 2005/10/17 02:21:37 dan Exp $ -->
<!-- XML thingy for man pages -->
<!ELEMENT MAN (NAME, SHORTDESCR, SYNOPSIS, 
PARAMETERS, DESCRIPTION, EXAMPLE?, SEE_ALSO?, AUTHOR?, BUGS?)>

<!ATTLIST MAN name CDATA #REQUIRED>

<!ELEMENT NAME        (#PCDATA)>
<!ELEMENT SHORTDESCR  (#PCDATA)>
<!ELEMENT SYNOPSIS    (#PCDATA)>
<!ELEMENT PARAMETERS  (RHS, LHS)>
<!ELEMENT RHS         (#PCDATA)>
<!ATTLIST RHS name CDATA #REQUIRED>

<!ELEMENT LHS         (#PCDATA)>
<!ATTLIST LHS name CDATA #REQUIRED>

<!ELEMENT ENUM        (ITEM, ITEMDESCR)>
<!ELEMENT ITEM        (#PCDATA)>
<!ELEMENT ITEMDESCR   (#PCDATA)>

<!ELEMENT DESCRIPTION (TEXT, VERB)>
<!ELEMENT TEXT        (#PCDATA)>
<!ELEMENT VERB        (#PCDATA)>

<!ELEMENT EXAMPLE     (SCICMD, STDCMD)>

<!ELEMENT SCIEX       (SCICMD, COMMENT)>
<!ELEMENT SCICMD      (#PCDATA)>
<!ELEMENT COMMENT     (#PCDATA)>

<!ELEMENT STDEX       (#PCDATA)>

<!ELEMENT SEE_ALSO    (TEXT*, ALSO*)>
<!ELEMENT ALSO        (#PCDATA)>

<!ELEMENT AUTHOR      (#PCDATA)>
<!ELEMENT BUGS        (#PCDATA)>

<!ENTITY copyright "Copyright (c) 2005, Dan McMahill">

=== dmcmahill/wcalc/sci-wcalc/stripline_syn.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE MAN SYSTEM "man.dtd">
<MAN>
<!-- $Id: stripline_syn.xml,v 1.3 2005/10/20 22:24:30 dan Exp $ -->
<!--
    Copyright (c) 2001, 2004, 2005 Dan McMahill
    All rights reserved.
   
    This code is derived from software written by Dan McMahill
   
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions
    are met:
    1. Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.
    2. Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in the
       documentation and   or other materials provided with the distribution.
    3. All advertising materials mentioning features or use of this software
       must display the following acknowledgement:
           This product includes software developed by Dan McMahill
     4. The name of the author may not be used to endorse or promote products
        derived from this software without specific prior written permission.
    
     THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
     IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
     INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
     AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
     OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
     OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
     SUCH DAMAGE.
-->

<NAME>stripline_syn</NAME>

<SHORTDESCR>Symmetric stripline transmission line synthesis
</SHORTDESCR>

<SYNOPSIS>
[w_out,h_out,l_out,er_out] = 
    stripline_syn(z0,elen,w,h,l,tmet,rho,rough,er,tand,f,flag);
</SYNOPSIS>

<PARAMETERS>
  <RHS name="z0">desired characteristic impedance (Ohms)</RHS>
  <RHS name="w">width of stripline line (meters)</RHS>
  <RHS name="h">substrate thickness (meters)</RHS>
  <RHS name="l">lentgh of stripline line (meters)</RHS>
  <RHS name="tmet">metal thickness (meters)</RHS>
  <RHS name="rho">resistivity of the metalization (relative to copper)</RHS>
  <RHS name="rough">conductor surface roughness (meters-rms)</RHS>
  <RHS name="er">substrate relative permitivitty</RHS>
  <RHS name="tand">substrate loss tangent</RHS>
  <RHS name="f">synthesis frequency (Hz)</RHS>
  <RHS name="flag">indicates which parameters should be optimized
    <ENUM>
      <ITEM name="flag=1">synthesize the metal width</ITEM>
      <ITEM name="flag=1">synthesize the substrate thickness</ITEM>
      <ITEM name="flag=2">synthesize the substrate dielectric constant</ITEM>
      <ITEM name="flag=3">synthesize the metal length</ITEM>
    </ENUM>
  </RHS>
</PARAMETERS>

<DESCRIPTION>
Function to synthesize the physical dimenstions of a single
stripline transmission line to achieve a desired characteristic
impedance and electrical length.  The desired characteristic
impedance and some of the physical
dimensions of the stripline line are given as inputs and the
remaining dimensions are calculated.


<VERB>

    XXXXXXXXXXXXXXXXX ground XXXXXXXXXXXXXXXXXXXXX
    ----------------------------------------------
   (  dielectric,er         \/           /|\     (
    )             -------   --            |       )
   (             | metal | Tmet           | H    (
    )             -------   --            |       )
   (             &lt;---W---&gt;  /\           \|/     (
    ----------------------------------------------
    XXXXXXXXXXXXXXXXX ground XXXXXXXXXXXXXXXXXXXXX

</VERB>
</DESCRIPTION>

<EXAMPLE>
  <SCIEX><SCICMD>sf=25.4e-6;</SCICMD>   <COMMENT>mils to meters conversion factor</COMMENT></SCIEX>
  <SCIEX><SCICMD>z0=75;</SCICMD>        <COMMENT>desired impedance</COMMENT></SCIEX>
  <SCIEX><SCICMD>elen=90;</SCICMD>      <COMMENT>desired electrical length (degrees)</COMMENT></SCIEX>
  <SCIEX><SCICMD>w=0;</SCICMD>          <COMMENT>width (we'll synthesize this)</COMMENT></SCIEX>
  <SCIEX><SCICMD>h=62*sf;</SCICMD>      <COMMENT>height</COMMENT></SCIEX>
  <SCIEX><SCICMD>l=1100*sf;</SCICMD>    <COMMENT>length</COMMENT></SCIEX>
  <SCIEX><SCICMD>tmet=1.4*sf;</SCICMD>  <COMMENT>metal thickness</COMMENT></SCIEX>
  <SCIEX><SCICMD>rho=1.72e-8;</SCICMD>  <COMMENT>resitivity</COMMENT></SCIEX>
  <SCIEX><SCICMD>rough=0.05*sf;</SCICMD><COMMENT>metal surface roughness</COMMENT></SCIEX>
  <SCIEX><SCICMD>er=4.5;</SCICMD>       <COMMENT>relative dielectric constant</COMMENT></SCIEX>
  <SCIEX><SCICMD>tand=0.01;</SCICMD>    <COMMENT>loss tangent</COMMENT></SCIEX>
  <SCIEX><SCICMD>f=2.4e9;</SCICMD>      <COMMENT>frequency</COMMENT></SCIEX>
  <SCIEX><SCICMD>flag=0;</SCICMD>       <COMMENT>synthesize width</COMMENT></SCIEX>
  <SCIEX><SCICMD>[w_out,h_out,l_out,er_out] = ...</SCICMD></SCIEX>
  <SCIEX><SCICMD>  stripline_syn(z0,elen,w,h,l,tmet,rho,rough,er,tand,f,flag);</SCICMD></SCIEX>
  <SCIEX><SCICMD>disp(sprintf('w=%g mils, l=%g mils',w_out/sf,l_out/sf));</SCICMD></SCIEX>
  <SCIEX><SCICMD>disp(sprintf('er=%g',er_out));</SCICMD></SCIEX>
  <SCIEX><SCICMD>disp(sprintf('z0=%g ohms, length=%g degrees',z0,elen));</SCICMD></SCIEX>
       <STDEX>
* 30.00 Ohms
stripline_syn 30.0 90.0 2.933e-3 2.0e-3 1.0 3e-5 1.72e-8 0.0 2.55  0.001 1e9 0
* 30.00 Ohms
stripline_syn 30.0 90.0 1.060e-3 2.0e-3 1.0 1e-5 1.72e-8 0.0 10.20 0.001 1e9 0
* 50.00 Ohms
stripline_syn 50.0 90.0 1.397e-3 2.0e-3 1.0 3e-5 1.72e-8 0.0 2.55  0.001 1e9 0
* 50.00 Ohms
stripline_syn 50.0 90.0 0.335e-3 2.0e-3 1.0 1e-5 1.72e-8 0.0 10.20 0.001 1e9 0
* 75.00 Ohms
stripline_syn 75.0 90.0 0.643e-3 2.0e-3 1.0 1e-5 1.72e-8 0.0 2.55  0.001 1e9 0
* 75.00 Ohms
stripline_syn 75.0 90.0 0.075e-3 2.0e-3 1.0 3e-5 1.72e-8 0.0 10.20 0.001 1e9 0
*
       </STDEX>
</EXAMPLE>

<SEE_ALSO>
   <ALSO>air_coil_calc</ALSO>
   <ALSO>air_coil_syn</ALSO>
   <ALSO>coax_calc</ALSO>
   <ALSO>coax_syn</ALSO>
   <ALSO>coupled_microstrip_calc</ALSO>
   <ALSO>coupled_microstrip_syn</ALSO>
   <ALSO>ic_microstrip_calc</ALSO>
   <ALSO>ic_microstrip_syn</ALSO>
   <ALSO>microstrip_calc</ALSO>
   <ALSO>microstrip_syn</ALSO>
   <ALSO>stripline_calc</ALSO>
   <ALSO>stripline_syn</ALSO>
</SEE_ALSO>

<AUTHOR>
Dan McMahill
</AUTHOR>

<BUGS>
None known
</BUGS>

</MAN>

=== dmcmahill/wcalc/sci-wcalc/coupled_microstrip_syn.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE MAN SYSTEM "man.dtd">
<MAN>
<!-- $Id: coupled_microstrip_syn.xml,v 1.3 2005/10/20 22:24:26 dan Exp $ -->
<!--
    Copyright (c) 2001, 2004, 2005 Dan McMahill
    All rights reserved.
   
    This code is derived from software written by Dan McMahill
   
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions
    are met:
    1. Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.
    2. Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in the
       documentation and   or other materials provided with the distribution.
    3. All advertising materials mentioning features or use of this software
       must display the following acknowledgement:
           This product includes software developed by Dan McMahill
     4. The name of the author may not be used to endorse or promote products
        derived from this software without specific prior written permission.
    
     THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
     IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
     INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
     AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
     OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
     OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
     SUCH DAMAGE.
-->

<NAME>coupled_microstrip_syn</NAME>

<SHORTDESCR>Coupled microstrip transmission line synthesis
</SHORTDESCR>

<SYNOPSIS>
[w_out,s_out,l_out] = 
    coupled_microstrip_syn(z0,k,elen,w,s,h,l,tmet,rho,rough,er,tand,f,0);
[w_out,s_out,l_out] = 
    coupled_microstrip_syn(z0e,z0o,elen,w,s,h,l,tmet,rho,rough,er,tand,f,1);
</SYNOPSIS>

<PARAMETERS>
  <RHS name="z0">desired characteristic impedance (Ohms)</RHS>
  <RHS name="k">desired coupling coefficient</RHS>
  <RHS name="z0e">desired even mode characteristic impedance (Ohms)</RHS>
  <RHS name="z0o">desired odd mode characteristic impedance (Ohms)</RHS>
  <RHS name="w">width of coupled microstrip line (meters)</RHS>
  <RHS name="s">spacing between coupled microstrip lines (meters)</RHS>
  <RHS name="h">substrate thickness (meters)</RHS>
  <RHS name="l">length of coupled_microstrip line (meters)</RHS>
  <RHS name="tmet">metal thickness (meters)</RHS>
  <RHS name="rho">resistivity of wire (relative to copper)</RHS>
  <RHS name="rough">conductor surface roughness (meters-rms)</RHS>
  <RHS name="er">substrate relative permitivitty</RHS>
  <RHS name="tand">substrate loss tangent</RHS>
  <RHS name="f">synthesis frequency (Hz)</RHS>
  <RHS name="flag">indicates which parameters should be optimized
    <ENUM>
      <ITEM name="flag=0">synthesize based on characteristic impedance and coupling coefficient</ITEM>
      <ITEM name="flag=1">synthesize based on even and odd mode characteristic impedances</ITEM>
    </ENUM>
  </RHS>

  <LHS name="w_out">calculated metal width</LHS>
  <LHS name="s_out">calculated gap</LHS>
  <LHS name="l_out">calculated metal length</LHS>
</PARAMETERS>

<DESCRIPTION>
Function to synthesize the physical dimenstions of a
coupled microstrip transmission line to achieve a desired characteristic
impedance and electrical length.  The desired characteristic
impedance and some of the physical
dimensions of the coupled_microstrip line are given as inputs and the
remaining dimensions are calculated.

The line may be specified either in terms of an even mode and
odd mode characteristic impedance or a characteristic impedance and 
coupling coefficient.

The model accounts for dispersion (frequency dependent propagation
velocity).

<VERB>

              |&lt;--W--&gt;|&lt;-S-&gt;|&lt;--W--&gt;|
               _______       -------
              | metal |     | metal | &lt;- rho,rough
    ----------------------------------------------
   (  dielectric                         /|\     (
    )   er,tand                       H   |       )
   (                                     \|/     (
    ----------------------------------------------
    XXXXXXXXXXXXXXXXXX ground XXXXXXXXXXXXXXXXXXXX

</VERB>

</DESCRIPTION>

<EXAMPLE>

  <SCIEX><SCICMD>sf=25.4e-6;</SCICMD>   <COMMENT>mils to meters conversion factor</COMMENT></SCIEX>
  <SCIEX><SCICMD>z0=75;</SCICMD>        <COMMENT>desired impedance </COMMENT></SCIEX>
  <SCIEX><SCICMD>k=0.3;</SCICMD>        <COMMENT>desired coupling</COMMENT></SCIEX>
  <SCIEX><SCICMD>elen=90;</SCICMD>      <COMMENT>desired electrical length (degrees)</COMMENT></SCIEX>
  <SCIEX><SCICMD>w=0;</SCICMD>          <COMMENT>width (we'll synthesize this)</COMMENT></SCIEX>
  <SCIEX><SCICMD>s=0;</SCICMD>          <COMMENT>spacing (we'll synthesize this)</COMMENT></SCIEX>
  <SCIEX><SCICMD>h=15*sf;</SCICMD>      <COMMENT>height</COMMENT></SCIEX>
  <SCIEX><SCICMD>l=1100*sf;</SCICMD>    <COMMENT>length</COMMENT></SCIEX>
  <SCIEX><SCICMD>tmet=1.4*sf;</SCICMD>  <COMMENT>metal thickness</COMMENT></SCIEX>
  <SCIEX><SCICMD>rho=1.72e-8;</SCICMD>  <COMMENT>resitivity of copper</COMMENT></SCIEX>
  <SCIEX><SCICMD>rough=0.05*sf;</SCICMD><COMMENT>metal surface roughness</COMMENT></SCIEX>
  <SCIEX><SCICMD>er=4.5;</SCICMD>       <COMMENT>relative dielectric constant</COMMENT></SCIEX>
  <SCIEX><SCICMD>tand=0.01;</SCICMD>    <COMMENT>loss tangent</COMMENT></SCIEX>
  <SCIEX><SCICMD>f=2.4e9;</SCICMD>      <COMMENT>frequency</COMMENT></SCIEX>
  <SCIEX><SCICMD>flag=0;</SCICMD>       <COMMENT>synthesize from z0 and k (instead</COMMENT></SCIEX>
  <SCIEX><SCICMD>       </SCICMD>       <COMMENT>of z0e and z0o)</COMMENT></SCIEX>
  <SCIEX><SCICMD>[w_out,s_out,l_out] = ...</SCICMD></SCIEX>
  <SCIEX><SCICMD>    coupled_microstrip_syn(z0,k,elen,w,s,h,l,tmet,rho,rough,er,tand,f,flag);</SCICMD></SCIEX>
  <SCIEX><SCICMD>disp(sprintf('w=%8.4g mils, s=%8.4g mils, l=%8.4g mils',w_out/sf,s_out/sf,l_out/sf));</SCICMD></SCIEX>

  <STDEX>
* ze = 55.27, zo = 45.23, ke = 2.261, ko = 2.009
coupled_microstrip_syn 50.000 0.1000 90 2.763e-3 1.213e-3 1e-3 1.0 0.0 1.72e-8 0.0 2.55 0.0 6e9 0
coupled_microstrip_syn 55.277 45.227 90 2.763e-3 1.213e-3 1e-3 1.0 0.0 1.72e-8 0.0 2.55 0.0 6e9 1
*
  </STDEX>
</EXAMPLE>

<SEE_ALSO>
   <ALSO>air_coil_calc</ALSO>
   <ALSO>air_coil_syn</ALSO>
   <ALSO>coax_calc</ALSO>
   <ALSO>coax_syn</ALSO>
   <ALSO>coupled_microstrip_calc</ALSO>
   <ALSO>coupled_microstrip_syn</ALSO>
   <ALSO>ic_microstrip_calc</ALSO>
   <ALSO>ic_microstrip_syn</ALSO>
   <ALSO>microstrip_calc</ALSO>
   <ALSO>microstrip_syn</ALSO>
   <ALSO>stripline_calc</ALSO>
   <ALSO>stripline_syn</ALSO>
</SEE_ALSO>

<AUTHOR>
Dan McMahill
</AUTHOR>

<BUGS>
None known
</BUGS>

</MAN>

=== dmcmahill/wcalc/sci-wcalc/coupled_microstrip_calc.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE MAN SYSTEM "man.dtd">
<MAN>
<!-- $Id: coupled_microstrip_calc.xml,v 1.2 2005/10/19 03:14:08 dan Exp $ -->
<!--
    Copyright (c) 2001, 2004, 2005 Dan McMahill
    All rights reserved.
   
    This code is derived from software written by Dan McMahill
   
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions
    are met:
    1. Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.
    2. Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in the
       documentation and   or other materials provided with the distribution.
    3. All advertising materials mentioning features or use of this software
       must display the following acknowledgement:
           This product includes software developed by Dan McMahill
     4. The name of the author may not be used to endorse or promote products
        derived from this software without specific prior written permission.
    
     THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
     IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
     INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
     BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
     AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
     OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
     OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
     SUCH DAMAGE.
-->

<NAME>coupled_microstrip_calc</NAME>

<SHORTDESCR>Coupled microstrip transmission line analysis
</SHORTDESCR>

<SYNOPSIS>
[z0,k,z0e,z0o,kev,kodd] = 
  coupled_microstrip_calc(w,s,h,l,tmet,rho,rough,er,tand,f);
</SYNOPSIS>

<PARAMETERS>
  <RHS name="w">width of coupled microstrip lines (meters)</RHS>
  <RHS name="s">spacing between coupled microstrip lines (meters)</RHS>
  <RHS name="h">substrate thickness (meters)</RHS>
  <RHS name="l">lentgh of coupled microstrip line (meters)</RHS>
  <RHS name="tmet">metal thickness (meters)</RHS>
  <RHS name="rho">resistivity of the metal (ohm-meters)</RHS>
  <RHS name="rough">conductor surface roughness (meters-rms)</RHS>
  <RHS name="er">substrate relative permitivitty</RHS>
  <RHS name="tand">substrate loss tangent</RHS>
  <RHS name="f">analysis frequency (Hz)</RHS>

  <LHS name="z0">calculated characteristic impedance (Ohms)</LHS>
  <LHS name="k">calculated coupling coefficient</LHS>
  <LHS name="z0e">calculated even mode characteristic impedance (Ohms)</LHS>
  <LHS name="z0o">calculated odd mode characteristic impedance (Ohms)</LHS>
  <LHS name="kev">calculated even mode effective relative permitivitty</LHS>
  <LHS name="kev">calculated odd mode effective relative permitivitty</LHS>
  <LHS name="loss">calculated loss of the line (dB)</LHS>
  <LHS name="deltal">calculated open circuit end correction (meters)</LHS>
</PARAMETERS>

<DESCRIPTION>
Function to analyze the electrical characteristics of a 
coupled microstrip transmission line. The physical
dimensions of the coupled microstrip line are given as inputs and the
characteristic impedance, effective dielectric constant, loss and
open circuit end correction are calculated.

The model accounts for dispersion (frequency dependent propagation
velocity).

<VERB>

              |&lt;--W--&gt;|&lt;-S-&gt;|&lt;--W--&gt;|
               _______       -------
              | metal |     | metal | &lt;- rho,rough
    ----------------------------------------------
   (  dielectric                         /|\\     (
    )   er,tand                       H   |       )
   (                                     \\|/     (
    ----------------------------------------------
    XXXXXXXXXXXXXXXXXX ground XXXXXXXXXXXXXXXXXXXX

</VERB>
</DESCRIPTION>

<EXAMPLE>

  <SCIEX><SCICMD>sf=25.4e-6;</SCICMD>   <COMMENT>mils to meters conversion factor</COMMENT></SCIEX>
  <SCIEX><SCICMD>w=20*sf;</SCICMD>      <COMMENT>width </COMMENT></SCIEX>
  <SCIEX><SCICMD>s=8*sf;</SCICMD>       <COMMENT>spacing</COMMENT></SCIEX>
  <SCIEX><SCICMD>h=15*sf;</SCICMD>      <COMMENT>height</COMMENT></SCIEX>
  <SCIEX><SCICMD>l=1100*sf;</SCICMD>    <COMMENT>length</COMMENT></SCIEX>
  <SCIEX><SCICMD>tmet=1.4*sf;</SCICMD>  <COMMENT>metal thickness</COMMENT></SCIEX>
  <SCIEX><SCICMD>rho=1;</SCICMD>        <COMMENT>resitivity relative to copper</COMMENT></SCIEX>
  <SCIEX><SCICMD>rough=0.05*sf;</SCICMD><COMMENT>metal surface roughness</COMMENT></SCIEX>
  <SCIEX><SCICMD>er=4.5;</SCICMD>       <COMMENT>relative dielectric constant</COMMENT></SCIEX>
  <SCIEX><SCICMD>tand=0.01;</SCICMD>    <COMMENT>loss tangent</COMMENT></SCIEX>
  <SCIEX><SCICMD>f=2.4e9;</SCICMD>      <COMMENT>frequency</COMMENT></SCIEX>
  <SCIEX><SCICMD>[z0,k,z0e,z0o,kev,kodd] = ...</SCICMD></SCIEX>
  <SCIEX><SCICMD>  coupled_microstrip_calc(w,s,h,l,tmet,rho,rough,er,tand,f);</SCICMD></SCIEX>
  <SCIEX><SCICMD>disp(sprintf('z0=%g Ohms, k=%g',z0,k));</SCICMD></SCIEX>
  <SCIEX><SCICMD>disp(sprintf('z0e=%g Ohms, z0o=%g Ohms',z0e,z0o));</SCICMD></SCIEX>
  <SCIEX><SCICMD>disp(sprintf('kev=%g, kodd=%g',kev,kodd));</SCICMD></SCIEX>

  <STDEX>
*
* ze = 55.27, zo = 45.23, ke = 2.261, ko = 2.009
coupled_microstrip_calc 2.763e-3 1.213e-3 1e-3 1.0 0.0 1.72e-8 0.0 2.55 0.0 6e9
* ze = 69.37, zo = 36.04, ke = 2.239, ko = 1.882
coupled_microstrip_calc 2.314e-3 0.123e-3 1e-3 1.0 0.0 1.72e-8 0.0 2.55 0.0 6e9
* ze = 86.74, zo = 28.82, ke = 2.180, ko = 1.833
coupled_microstrip_calc 1.744e-3 0.988e-5 1e-3 1.0 0.0 1.72e-8 0.0 2.55 0.0 6e9
*
  </STDEX>
</EXAMPLE>

<SEE_ALSO>
   <ALSO>air_coil_calc</ALSO>
   <ALSO>air_coil_syn</ALSO>
   <ALSO>coax_calc</ALSO>
   <ALSO>coax_syn</ALSO>
   <ALSO>coupled_microstrip_calc</ALSO>
   <ALSO>coupled_microstrip_syn</ALSO>
   <ALSO>ic_microstrip_calc</ALSO>
   <ALSO>ic_microstrip_syn</ALSO>
   <ALSO>microstrip_calc</ALSO>
   <ALSO>microstrip_syn</ALSO>
   <ALSO>stripline_calc</ALSO>
   <ALSO>stripline_syn</ALSO>
</SEE_ALSO>

<AUTHOR>
Dan McMahill
</AUTHOR>

<BUGS>
None known
</BUGS>

</MAN>
